# Generated by Django 6.0 on 2025-12-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Drafts', 'Drafts'), ('Published', 'Published')], default='Drafts', max_length=20),
        ),
    ]
